---
name: snappy-managed-service
director_uuid: 

releases:
- name: snappy-managed-service
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.0.0/28
    reserved: [10.244.0.1]
    cloud_properties:
      name: random

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: snappydata_locator
  templates:
  - name: snappydata_locator
  instances: 2
  resource_pool: default
  networks:
  - name: default
  properties: {}
- name: snappydata_server
  templates:
  - name: snappydata_server
  instances: 2
  resource_pool: default
  networks:
  - name: default
  properties: {}
- name: snappydata_lead
  templates:
  - name: snappydata_lead
  instances: 2
  resource_pool: default
  networks:
  - name: default
  properties: {}

